FROM node:14

# Set the working directory
WORKDIR /index

# Copy package.json and yarn.lock to the working directory
COPY package.json yarn.lock ./

# Install dependencies
RUN yarn install

# Copy the rest of the application code
COPY . .

# Expose a port (if needed)
EXPOSE 8000

# Command to run when the container starts
CMD ["yarn", "run", "dev"]
